### ISSUE TITLE
Missing headers

### ISSUE THREAD

**Issue by xinthose** [ncd-io/MCP23017#1]
https://github.com/ncd-io/MCP23017/blob/5eed4ca79e85844fe68e41ff48279e27740f206d/Particle/MCP23017.h#L1-L3
https://github.com/ncd-io/MCP23017/blob/5eed4ca79e85844fe68e41ff48279e27740f206d/Particle/MCP23017.cpp#L3

Hello.  Sketch will not compile without these files.  Where can I get them?  Can I not use this library with Arduino?

**Comment by telliottosceola** [comment]
Hi,

I also replied to your issue on the NCD1Relay.  These library headers are core for Particle.  You can get more info from https://partile.io. If you wish to use this library with Arduino some slight porting would be required but it would not be significant.

**Comment by xinthose** [comment]
OK.  Thank you sir.
